# Generated by Django 4.2.3 on 2023-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_item_quantity_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
