# Generated by Django 4.2.3 on 2023-07-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_itemreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_review',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
    ]
